version: 2

jobs:
  tests:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
         keys:
           - v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
         key: v1-yarn-{{ checksum "yarn.lock" }}
         paths:
           - node_modules/
      - run: yarn test

  lint:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
         keys:
           - v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
         key: v1-yarn-{{ checksum "yarn.lock" }}
         paths:
           - node_modules/
      - run: yarn lint

  typescript:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
         keys:
           - v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
         key: v1-yarn-{{ checksum "yarn.lock" }}
         paths:
           - node_modules/
      - run: yarn tsc

  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
         keys:
           - v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
         key: v1-yarn-{{ checksum "yarn.lock" }}
         paths:
           - node_modules/
      - run: yarn build 

workflows:
  version: 2

  build:
    jobs:
      - tests
      - lint
      - tsc
      - build
